spring.application.name=spring-rush-a1

# spring.datasource.url=jdbc:postgresql://localhost:5432/rush
# spring.datasource.username=postgres
# spring.datasource.password=password

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# H2 Database Connection
spring.datasource.url=jdbc:h2:mem:socialdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Settings (Access at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true